---
k3s_config_dir: /etc/rancher/k3s
k3s_server_url: "https://{{ groups['k3s_servers'][0] }}:6443"
k3s_token: "{{ vault_k3s_token }}"
k3s_node_labels: []
k3s_node_taints: []
k3s_agent_extra_args: ""
k3s_install_script_url: "https://get.k3s.io"
k3s_version: "v1.28.0+k3s1"
k3s_kubeconfig_mode: "644"
