---
# Node Exporter Role Defaults

node_exporter_version: "1.7.0"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_install_dir: "/usr/local/bin"
node_exporter_config_dir: "/etc/node_exporter"
node_exporter_data_dir: "/var/lib/node_exporter"
node_exporter_port: 9100
node_exporter_service_name: "node-exporter"